#!/bin/bash

trap "exit" INT

SPEAKER_MAC="0F:80:0D:23:60:F8"

while true; do
    # Check if connected
    if ! bluetoothctl info $SPEAKER_MAC | grep -q "Connected: yes"; then
        bluetoothctl connect $SPEAKER_MAC
    fi
    sleep 30
done
